[package]
name = "ramfiller"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Very quickly fill a desired amount of RAM"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
